config/routes.rb
Rails.application.routes.draw do
  constraints(Weby::Subdomain) do

    get '/' => 'sites#show', as: :site
    get '/admin' => 'sites#admin', as: :site_admin
    get '/admin/edit' => 'sites#edit', as: :edit_site_admin
    get '/map' => 'sites/pages#sitemap', as: :sitemap_site_pages
    patch '/admin/edit' => 'sites#update', as: :update_site_admin
    delete '/admin/subsites/:id' => 'sites#destroy_subsite', as: :destroy_subsite_admin
    patch '/admin/subsites/:id' => 'sites#update_subsite', as: :update_subsite_admin

    resources :pages, as: :site_pages, controller: 'sites/pages', path: 'p', only: [:show]
    get '/fp', to: 'sites/pages#frame'
    get :pages, to: 'sites/pages#index', as: :site_pages
    get '/search', to: 'sites/searches#index', as: :searches
    #old routes
    get 'pages/:id(-:title)' => 'sites/pages#redirect', constraints: {id: /\d+/}

    resources :components,
              as: :site_components,
              controller: 'sites/components',
              only: [:show]

    post 'count/:model/:id' => 'application#count_click', as: :count_click

    namespace :admin, module: 'sites/admin', as: :site_admin do

      # route to paginate
      get 'repositories/page/:page' => 'repositories#index'
      get 'pages/page/:page' => 'pages#index'

      get 'stats' => 'statistics#index'
      get 'backups' => 'backups#index'
      get 'generate' => 'backups#generate'
      post 'import' => 'backups#import'

      resources :activity_records, only: [:index, :show]
      resources :extensions
      resources :menus do
        collection do
          post :change_order
        end
        resources :menu_items, controller: 'menus/menu_items' do
          member do
            put :toggle
          end
          collection do
            post :change_order, :change_menu
            delete :destroy_many
          end
        end
      end
      resources :pages do
        member do
          put :toggle, :recover
        end
        collection do
          get :recycle_bin
          delete :empty_bin, :destroy_many
        end
      end
      resources :repositories do
        member do
          get :crop
          put :recover
        end
        collection do
          get :recycle_bin
          delete :empty_bin, :destroy_many
        end
      end
      resources :roles, except: [:show] do
        collection do
          put :index
        end
      end
      resources :skins do
        member do
          post :apply
          get :preview
        end
        resources :components do
          member do
            put :toggle
            post :clone
          end
          collection do
            post :sort
            delete :destroy_many
          end
        end
        resources :styles do
          member do
            put :toggle, :copy, :follow, :unfollow
          end
          collection do
            post :sort
            delete :destroy_many
          end
        end
      end
      resources :users, only: [] do
        collection do
          get :manage_roles, :search
          post :change_roles, :create_local_admin_role, :set_preferences
          delete :destroy_local_admin_role
        end
      end
      resources :layouts, only: [] do
        collection do
          get :settings
          patch :settings, action: "update_settings"
        end
      end
    end

    Weby.extensions.each do |name, extension|
      constraints(extension) do
        require "#{name.to_s}/routes"
        instance_eval &("#{name.to_s.classify}::Routes".constantize.load)
      end
    end
  end

  root to: 'sites#index'

  constraints(Weby::GlobalDomain) do
    # route to paginate
    get 'sites/page/:page' => 'sites#index', as: :sites

    get '/admin' => 'application#admin'

    namespace :admin do
      match 'settings' => 'settings#index', via: [:get, :put]
      post 'settings/exec' => 'settings#exec', as: :exec
      resources :users do
        collection do
          get :manage_roles, :search
          post :change_roles
        end
        member do
          put :toggle
          put :set_admin
        end
      end
      resources :roles, except: :show do
        collection do
          put :index
          post :sort
        end
      end
      resources :sites, except: [:show] do
        member do
          put :toggle
          post :reindex
        end
      end
      resources :groupings, except: [:show]
      resources :notifications
      resources :activity_records, only: [:index, :show, :destroy]

      get 'stats' => 'statistics#index'

      # route to paginate
      get 'users/page/:page' => 'users#index'
      get 'sites/page/:page' => 'sites#index'
    end
  end

  # routes to profiles
  resources :profiles, only: [:show, :edit, :update], constraints: {id: /[^\/]+/} do
    member do
      get :history
    end
  end

  resources :notifications, only: [:index, :show] do
    collection do
      post :mark_as_read
    end
  end

  # defaults devise routes
  devise_for :users,
    path: '/',
    skip: [:sessions, :registrations, :passwords],
    controllers: { omniauth_callbacks: 'omniauth_callbacks' }

  # customize devise routes
  devise_scope :user do
    # routes to session
    delete 'logout'  => 'sessions#destroy'
    get 'login'   => 'sessions#new'
    post 'login'   => 'sessions#create'
    post 'link_user' => 'sessions#link_user'
    get 'new_user' => 'sessions#new_user'
    get 'shib_login/:hash' => 'sessions#shib_login', as: :shib_login

    # routes to register
    get 'signup'  => 'devise/registrations#new'
    post 'signup'  => 'registrations#create'

    # routes to password
    get 'forgot_password' => 'devise/passwords#new'
    post 'forgot_password' => 'passwords#create'
    get 'reset_password'  => 'devise/passwords#edit'
    put 'reset_password'  => 'devise/passwords#update'
  end

  get 'robots.txt' => 'sites#robots', format: 'txt'
  get '*not_found' => 'application#render_404'
end

app/models/menu.rb
class Menu < ApplicationRecord
  belongs_to :site

  has_many :menu_items, -> { order(:position).includes(:i18ns) }, dependent: :destroy
  has_many :root_menu_items, -> { order(:position).includes(:i18ns).where('parent_id is NULL') }, class_name: 'MenuItem'

  validates :name, :site, presence: true

  scope :with_items, -> { includes(:menu_items) }

  # Returns a hash, with the parent_id and a array as the value
  # ie. {0 => [menuitem1, menuitem2}, 1 => [menuitem3,menuitem4] }
  def items_by_parent(published = false)
    if published
      menu_items.published.group_by(&:parent_id)
    else
      menu_items.group_by(&:parent_id)
    end
  end

  def self.import(attrs, _options = {})
    return attrs.each { |attr| import attr } if attrs.is_a? Array

    attrs = attrs.dup
    attrs = attrs['menu'] if attrs.key? 'menu'
    id = attrs['id']
    attrs.except!('id', 'created_at', 'updated_at', 'site_id', '@type', 'type')
    items = attrs.delete('root_menu_items')

    menu = self.create!(attrs)

    if menu.persisted?
      Import::Application::CONVAR["menu"]["#{id}"] ||= "#{menu.id}"
    end

    menu.menu_items.import items if menu.persisted?
  end
end

app/controllers/sites/admin/menus/menu_items_controller.rb
class Sites::Admin::Menus::MenuItemsController < ApplicationController
  before_action :get_current_menu
  before_action :require_user
  before_action :check_authorization

  include ActsToToggle

  respond_to :html, :xml, :js

  def index
    redirect_to site_admin_menus_path(menu: @menu.id)
  end

  def show
    redirect_to site_admin_menus_path(menu: @menu.id)
  end

  def new
    @menu_item = @menu.menu_items.new_or_clone(params[:copy_from], parent_id: params[:parent_id])
    @menu_item_parent = @menu_item.parent
  end

  def create
    @menu_item = @menu.menu_items.new(menu_item_params)
    @menu_item.position = @menu.menu_items.where(parent_id: @menu_item.parent_id).maximum(:position).to_i + 1

    if @menu_item.save
      flash[:success] = t('successfully_created')
      record_activity('created_menu_item', @menu_item)
      redirect_to site_admin_menus_path(menu: @menu.id)
    else
      @menu_item_parent = @menu_item.parent
      render action: :new
    end
  end

  def edit
    @menu_item = @menu.menu_items.find(params[:id])
  end

  def update
    @menu_item = @menu.menu_items.find(params[:id])
    if @menu_item.update(menu_item_params)
      flash[:success] = t('successfully_updated')
      record_activity('updated_menu_item', @menu_item)
      redirect_to site_admin_menus_path(menu: @menu.id)
    else
      render action: :edit
    end
  end

  def destroy
    @menu_item = @menu.menu_items.find(params[:id])
    message = {error: t('error_destroying_object')}
    if @menu_item.destroy
      record_activity('destroyed_menu_item', @menu_item)
      message = {success: t('successfully_deleted')}
    end
    redirect_back(flash: message, fallback_location: site_admin_menus_path(menu: @menu.id))
  end

  def destroy_many
    @menu.menu_items.where(id: params[:ids].split(',')).each do |menu_item|
      if menu_item.destroy
        record_activity('destroyed_menu_item', menu_item)
        flash[:success] = t('successfully_deleted')
      end
    end
    redirect_back(fallback_location: site_admin_menus_path(menu: @menu.id))
  end

  # Altera a ordenação do menu
  def change_order
    @menu_item = @menu.menu_items.find(params[:id])
    @menu_item.update_positions(params[:menu_item])
    head :ok
  end

  # Altera o menu de um item de menu, e todos seus descendentes
  def change_menu
    @menu_item = @menu.menu_items.find(params[:id])
    @menu_item.position = MenuItem.where('menu_id = ? AND parent_id is NULL', params[:new_menu_id]).maximum(:position).to_i + 1
    @menu_item.menu_id = params[:new_menu_id]
    @menu_item.parent_id = nil
    @menu_item.save!
    head :ok
  end

  private

  def get_current_menu
    @menu = current_site.menus.find(params[:menu_id])
  end

  def resource
    get_resource_ivar || set_resource_ivar(@menu.menu_items.find(params[:id]))
  end

  def menu_item_params
    params.require(:menu_item).permit(:url, :target_id, :parent_id, :target_type, :new_tab,
                                      :publish, :html_class, { i18ns_attributes: [:id, :locale_id, :title, :description] })
  end
end

app/controllers/sites/admin/menus_controller.rb
class Sites::Admin::MenusController < ApplicationController
  before_action :require_user
  before_action :check_authorization

  respond_to :html, :xml, :js
  def index
    @menus = current_site.menus
    @menu = params[:menu] ? @menus.select { |menu| menu.id == params[:menu].to_i }[0] : @menus.first
  end

  def show
    redirect_to site_admin_menus_path(menu: params[:id])
  end

  def new
    @menu = Menu.new
  end

  def create
    @menu = current_site.menus.new(menu_params)
    @menu.position = current_site.menus.maximum(:position).to_i + 1
    if @menu.save
      flash[:success] = t('successfully_created')
      record_activity('created_menu', @menu)
      redirect_to site_admin_menus_path(menu: @menu.id)
    else
      respond_with(:site_admin, @menu)
    end
  end

  def edit
    @menu = current_site.menus.find(params[:id])
  end

  def update
    @menu = current_site.menus.find(params[:id])
    if @menu.update(menu_params)
      flash[:success] = t('successfully_updated')
      record_activity('updated_menu', @menu)
      redirect_to site_admin_menus_path(menu: @menu.id)
    else
      respond_with(:site_admin, @menu)
    end
  end

  # Altera a ordenação do menu
  def change_order
    position = 0
    params[:menu].each do |menu_id|
      current_site.menus.find(menu_id).update_attribute(:position, position += 1)
    end
    head :ok
  end

  def destroy
    @menu = current_site.menus.find(params[:id])
    @menu.destroy
    flash[:success] = t('successfully_deleted')
    record_activity('destroyed_menu', @menu)
    redirect_to site_admin_menus_path
  end

  private

  def menu_params
    params.require(:menu).permit(:name)
  end
end

app/helpers/menus_helper.rb
module MenusHelper
  def acessibility_color_links(component)
    ''.tap do |html|
      if !component.label_contrast.blank?
        html << component.label_contrast
      end
      html << link_to("C", "#", class: "contrast_normal")
      html << link_to("C", "#", class: "contrast_blue", data: { url: asset_path('shared/contrast_blue.css') })
      html << link_to("C", "#", class: "contrast_black", data: { url: asset_path('shared/contrast_black.css') })
      html << link_to("C", "#", class: "contrast_yellow", data: { url: asset_path('shared/contrast_yellow.css') })
    end.html_safe
  end

  def acessibility_font_links(component)
    ''.tap do |html|
      if component.font_size?
        html << "<span class='accessibility_font'>"
        if !component.label_font_size.blank?
          html << component.label_font_size
        end
        html << link_to(weby_icon('plus'), "#", onclick: 'font_size_change("plus")', title: t(".increase_font_size"))
        html << link_to(weby_icon('font'), "#", onclick: 'font_size_original()', title: t(".default_font_size"))
        html << link_to(weby_icon('minus'), "#", onclick: 'font_size_change("minus")', title: t(".decrease_font_size"))
        html << "</span>"
      end
    end.html_safe
  end
end

app/views/sites/admin/menus/_form.html.erb
<%= simple_form_for [:site_admin, @menu] do |f| %>
  <%= f.show_errors %>

  <%= f.input :name,
    placeholder: t(".name"),
    input_html: {class: "name_input"} %>

  <div class="form-actions">
    <%= f.button :submit, class: 'btn btn-primary', disable_with: t("please_wait") %>
    <%= link_to t("back"), :back, class: "btn btn-default" %>
  </div>
<% end %> 

app/views/sites/admin/menus/edit.html.erb
<% title ".menus" %>
<% breadcrumb :menus_edit, @menu %>
<%= render 'form' %>

app/views/sites/admin/menus/index.html.erb
<% title ".menus" %>
<% breadcrumb :menus %>
<div class="row">
  <div class="<%= @menu ? 'col-md-3' : 'col-md-12' %>">
    <div class="add-menu">
      <% with_permission action: :new do %>
        <%= link_to icon('plus-sign', text: t(".new_menu")), new_site_admin_menu_path, class: "btn btn-success #{'btn-block' if @menu}" %>
      <% end %>
    </div>
    <% if @menus.empty? %>
      <div class="alert alert-warning">
        <%= t(".none_menu") %>
      </div>
    <% else %>
      <div class="list-group menu-tabs" id="tabs" data-url="<%= change_order_site_admin_menus_path %>">
        <% @menus.each do |menu| %>
          <% active = (menu==@menu ? "active" : "") %>
          <%= content_tag :li, class: "list-group-item #{active}", id: "menu_#{menu.id}", data: {menu_id: menu.id} do %>
            <%= image_tag('drag.png', class: 'handle') %>
            <%= link_to(menu.name.try(:titleize), menu==@menu ? '#' : site_admin_menus_path(menu: menu.id)) %>
            <%= render_dropdown_menu direction: 'bottom-right' do %>
              <%= link_to(icon('eye-open', text: t('show')), site_admin_menus_path(menu: menu.id), class: 'action-link') if menu!=@menu %>
              <%= make_menu(menu, except: :show) %>
            <% end %>
          <% end %>
        <% end %>
      </div>
    <% end %>
  </div>
  <% if @menu %>
    <div class="col-md-9">
      <div class="pull-right">
        <% with_permission controller: Sites::Admin::Menus::MenuItemsController, action: :new do %>
          <%= link_to icon('plus-sign', text: t(".new_menu_item")), new_site_admin_menu_menu_item_path(@menu), class: "btn btn-success" %>
        <% end %>
        <% with_permission action: :edit do %>
          <%#= link_to t("edit"), edit_site_admin_menu_path(@menu), class: "btn btn-default", title: t('edit') %>
        <% end %>
        <% with_permission action: :destroy do %>
          <%#= link_to t("destroy"), site_admin_menu_path(@menu), class: "btn btn-danger", data: { confirm: t('are_you_sure_del_item', item: @menu.screen_name) }, method: :delete, title: t('destroy') %>
        <% end %>
      </div>
      <div class="clearfix control-group"></div>
      <% if @menu.menu_items.empty? %>
        <div class="alert alert-warning">
          <%= t(".none_menu_item", menu: @menu.name) %>
        </div>
      <% else %>
        <div id="main-menu" data-sort-url="<%= change_order_site_admin_menu_menu_items_path(@menu) %>" data-change-url="<%= change_menu_site_admin_menu_menu_items_path(@menu) %>">
          <%= link_to t('.collapse', icon: icon('chevron-right')).html_safe, '#', class: 'expand-collapse', data: {alt_text: t('.expand', icon: icon('chevron-down')).html_safe} %>
          <%= print_menu(@menu, view_ctrl: true) %>
          <%= render_bulk_actions do %>
            <% with_permission(action: :destroy_many) do %>
              <%= link_to icon('trash', text: t('destroy')), destroy_many_site_admin_menu_menu_items_path(@menu), class: 'btn btn-sm btn-default destroy-many', method: :delete, data: {confirm: t('are_you_sure_del_many')} %>
            <% end %>
          <% end %>
        </div>
      <% end %>

      <% content_for :stylesheets, stylesheet_link_tag("sortable") %>
      <% content_for :javascripts, javascript_include_tag("init/sortable") %>
      <% content_for :javascripts, javascript_include_tag("menus.index") %>
    </div>
  <% end %>
</div>

app/views/sites/admin/menus/new.html.erb
<% title ".menus" %> 
<% breadcrumb :menus_new %>
<%= render 'form' %>