config/routes.rb
Rails.application.routes.draw do
  constraints(Weby::Subdomain) do

    get '/' => 'sites#show', as: :site
    get '/admin' => 'sites#admin', as: :site_admin
    get '/admin/edit' => 'sites#edit', as: :edit_site_admin
    get '/map' => 'sites/pages#sitemap', as: :sitemap_site_pages
    patch '/admin/edit' => 'sites#update', as: :update_site_admin
    delete '/admin/subsites/:id' => 'sites#destroy_subsite', as: :destroy_subsite_admin
    patch '/admin/subsites/:id' => 'sites#update_subsite', as: :update_subsite_admin

    resources :pages, as: :site_pages, controller: 'sites/pages', path: 'p', only: [:show]
    get '/fp', to: 'sites/pages#frame'
    get :pages, to: 'sites/pages#index', as: :site_pages
    get '/search', to: 'sites/searches#index', as: :searches
    #old routes
    get 'pages/:id(-:title)' => 'sites/pages#redirect', constraints: {id: /\d+/}

    resources :components,
              as: :site_components,
              controller: 'sites/components',
              only: [:show]

    post 'count/:model/:id' => 'application#count_click', as: :count_click

    namespace :admin, module: 'sites/admin', as: :site_admin do

      # route to paginate
      get 'repositories/page/:page' => 'repositories#index'
      get 'pages/page/:page' => 'pages#index'

      get 'stats' => 'statistics#index'
      get 'backups' => 'backups#index'
      get 'generate' => 'backups#generate'
      post 'import' => 'backups#import'

      resources :activity_records, only: [:index, :show]
      resources :extensions
      resources :menus do
        collection do
          post :change_order
        end
        resources :menu_items, controller: 'menus/menu_items' do
          member do
            put :toggle
          end
          collection do
            post :change_order, :change_menu
            delete :destroy_many
          end
        end
      end
      resources :pages do
        member do
          put :toggle, :recover
        end
        collection do
          get :recycle_bin
          delete :empty_bin, :destroy_many
        end
      end
      resources :repositories do
        member do
          get :crop
          put :recover
        end
        collection do
          get :recycle_bin
          delete :empty_bin, :destroy_many
        end
      end
      resources :roles, except: [:show] do
        collection do
          put :index
        end
      end
      resources :skins do
        member do
          post :apply
          get :preview
        end
        resources :components do
          member do
            put :toggle
            post :clone
          end
          collection do
            post :sort
            delete :destroy_many
          end
        end
        resources :styles do
          member do
            put :toggle, :copy, :follow, :unfollow
          end
          collection do
            post :sort
            delete :destroy_many
          end
        end
      end
      resources :users, only: [] do
        collection do
          get :manage_roles, :search
          post :change_roles, :create_local_admin_role, :set_preferences
          delete :destroy_local_admin_role
        end
      end
      resources :layouts, only: [] do
        collection do
          get :settings
          patch :settings, action: "update_settings"
        end
      end
    end

    Weby.extensions.each do |name, extension|
      constraints(extension) do
        require "#{name.to_s}/routes"
        instance_eval &("#{name.to_s.classify}::Routes".constantize.load)
      end
    end
  end

  root to: 'sites#index'

  constraints(Weby::GlobalDomain) do
    # route to paginate
    get 'sites/page/:page' => 'sites#index', as: :sites

    get '/admin' => 'application#admin'

    namespace :admin do
      match 'settings' => 'settings#index', via: [:get, :put]
      post 'settings/exec' => 'settings#exec', as: :exec
      resources :users do
        collection do
          get :manage_roles, :search
          post :change_roles
        end
        member do
          put :toggle
          put :set_admin
        end
      end
      resources :roles, except: :show do
        collection do
          put :index
          post :sort
        end
      end
      resources :sites, except: [:show] do
        member do
          put :toggle
          post :reindex
        end
      end
      resources :groupings, except: [:show]
      resources :notifications
      resources :activity_records, only: [:index, :show, :destroy]

      get 'stats' => 'statistics#index'

      # route to paginate
      get 'users/page/:page' => 'users#index'
      get 'sites/page/:page' => 'sites#index'
    end
  end

  # routes to profiles
  resources :profiles, only: [:show, :edit, :update], constraints: {id: /[^\/]+/} do
    member do
      get :history
    end
  end

  resources :notifications, only: [:index, :show] do
    collection do
      post :mark_as_read
    end
  end

  # defaults devise routes
  devise_for :users,
    path: '/',
    skip: [:sessions, :registrations, :passwords],
    controllers: { omniauth_callbacks: 'omniauth_callbacks' }

  # customize devise routes
  devise_scope :user do
    # routes to session
    delete 'logout'  => 'sessions#destroy'
    get 'login'   => 'sessions#new'
    post 'login'   => 'sessions#create'
    post 'link_user' => 'sessions#link_user'
    get 'new_user' => 'sessions#new_user'
    get 'shib_login/:hash' => 'sessions#shib_login', as: :shib_login

    # routes to register
    get 'signup'  => 'devise/registrations#new'
    post 'signup'  => 'registrations#create'

    # routes to password
    get 'forgot_password' => 'devise/passwords#new'
    post 'forgot_password' => 'passwords#create'
    get 'reset_password'  => 'devise/passwords#edit'
    put 'reset_password'  => 'devise/passwords#update'
  end

  get 'robots.txt' => 'sites#robots', format: 'txt'
  get '*not_found' => 'application#render_404'
end

app/models/role.rb
class Role < ApplicationRecord
  belongs_to :site, optional: true

  has_and_belongs_to_many :users

  validates :name, presence: true

  scope :globals, -> { where(site_id: nil) }
  scope :no_local_admin, -> { where("permissions != 'Admin' OR permissions is null") }

  def permissions_hash
    permissions.present? ? eval(permissions.to_s) : {}
  end
end

app/controllers/admin/roles_controller.rb
class Admin::RolesController < Admin::BaseController
  before_action :set_resource, only: [:edit, :update, :destroy]

  respond_to :html

  def index
    @roles = Role.globals.order('id')
    @rights = Weby::Rights.permissions.sort

    if request.put? # && params[:role]
      params[:role] ||= {}

      @roles.each do |role| # params[:role].each do |role, right|
        role.update(permissions: params[:role][role.id.to_s] ? params[:role][role.id.to_s]['permissions'].to_s : '{}')
      end

      flash[:success] = t('successfully_updated')
      redirect_to admin_roles_path
    end
  end

  def new
    @role = Role.new
  end

  def create
    @role = Role.new(role_params)
    @role.permissions ||= '{}'
    @role.save

    record_activity('created_global_role', @role)

    redirect_to admin_roles_path
  end

  def edit
  end

  def update
    @role.update(role_params)

    record_activity('updated_global_role', @role)

    redirect_to admin_roles_path
  end

  def destroy
    @role.destroy

    record_activity('destroyed_global_role', @role)

    redirect_back(fallback_location: admin_roles_path)
  end

  private

  def set_resource
    resource
  end

  def role_params
    params.require(:role).permit(:name)
  end
end

app/controllers/sites/admin/roles_controller.rb
class Sites::Admin::RolesController < ApplicationController
  before_action :require_user
  before_action :check_authorization

  respond_to :html
  def index
    @roles = current_site.roles.no_local_admin.order("id")
    @rights = Weby::Rights.permissions(current_site).sort

    if request.put? # && params[:role]
      params[:role] ||= {}
      @roles.each do |role| # params[:role].each do |role, right|
        role.update(permissions: params[:role][role.id.to_s] ? params[:role][role.id.to_s]['permissions'].to_s : '{}')
      end
      flash[:success] = t('successfully_updated')
      redirect_to site_admin_roles_path
    end
  end

  def edit
    @role = Role.find(params[:id])
  end

  def new
    @role = Role.new
    respond_with(:site_admin, @role)
  end

  def create
    @role = Role.new(role_params)
    @role.permissions ||= '{}'
    @role.save
    record_activity('created_role', @role)

    redirect_to site_admin_roles_path
  end

  def update
    @role = Role.find(params[:id])
    @role.update(role_params)
    record_activity('updated_role', @role)
    redirect_to site_admin_roles_path
  end

  def destroy
    @role = Role.find(params[:id])
    @role.destroy
    record_activity('destroyed_role', @role)
    redirect_back(fallback_location: site_admin_roles_path)
  end

  private

  def role_params
    params.require(:role).permit(:site_id, :name)
  end
end

app/views/admin/roles/_form.html.erb
<%= simple_form_for [:admin, @role] do |f| %>
  <%= f.show_errors %>

  <%= f.input :name  %>

  <div class="form-actions">
    <%= f.button :submit, class: 'btn btn-primary', disable_with: t("please_wait") %>
    <%= link_to t("back"), :back, class: "btn btn-default" %>
  </div>
<% end %>

app/views/admin/roles/_roles_table.html.erb
<% breadcrumb :roles %>
<p class="pull-right">
  <%= yield %>
</p>
<div class="clearfix"></div>

<% if @roles.present? %>

  <%= form_tag site_admin_roles_path, method: :put, id: 'roles_form' do %>

    <div class="maxi_layout space-top">

      <div class="maxi_level">
        <div class="placeholder">
          <div class="right-row header labels">
            <span class="placeholder-name right-name">
              <%= t(".roles_permissions") %>
              <%= render_dropdown_menu do %>
                <%= link_to(fa_icon('undo', text: t('.reset_all')), '#',
                      class: 'reset-all', title: t('.reset_all_hint')) %>
              <% end %>
            </span>
            <% @roles.each do |role| %>
              <span class="role-config">
                <span class="role-label">
                  <span>
                    <%= role.name %>
                  </span>
                  <%= render_dropdown_menu do %>
                    <% if check_permission(Admin::RolesController, [:show]) %>
                      <%= link_to icon('edit', text: t("edit")), edit_admin_role_path(role) %>
                    <% end %>
                    <%= link_to(fa_icon('toggle-on', text: t('.select_all_role')), '#',
                          class: 'check-all-role', title: t('.select_all_role_hint'), data: {role: role.id, chkd: true}) %>
                    <%= link_to(fa_icon('toggle-off', text: t('.unselect_all_role')), '#',
                          class: 'check-all-role', title: t('.unselect_all_role_hint'), data: {role: role.id, chkd: false}) %>
                    <%= link_to(fa_icon('undo', text: t('.reset_role')), '#',
                        class: 'reset-role', title: t('.reset_role_hint'),
                        data: {role: role.id}) %>
                    <% if check_permission(Admin::RolesController, [:destroy]) %>
                      <%= link_to icon('trash', text: t("destroy")), admin_role_path(role), :data => {:confirm => t("are_you_sure_del_item", item: role.name)}, :method => :delete %>
                    <% end %>
                  <% end %>
                </span>
              </span>
            <% end %>
          </div>
        </div>
      </div>

      <% @rights.each do |controller, permissions| %>
        <div class="maxi_level single">
          <div class="placeholder">
            <div class="right-row header">
              <span class="right-name">
                <span class="placeholder-name"><%= t(".#{controller}") %></span>
                <%= render_dropdown_menu do %>
                  <%= link_to(fa_icon('toggle-on', text: t('.select_group_rights')), '#',
                        class: 'check-group-rights', title: t('.select_group_rights_hint'),
                        data: {group: controller, chkd: true}) %>
                  <%= link_to(fa_icon('toggle-off', text: t('.unselect_group_rights')), '#',
                        class: 'check-group-rights', title: t('.unselect_group_rights_hint'),
                        data: {group: controller, chkd: false}) %>
                  <%= link_to(fa_icon('undo', text: t('.reset_group')), '#',
                        class: 'reset-group', title: t('.reset_group_hint'),
                        data: {group: controller}) %>
                <% end %>
              </span>
              <% @roles.each do |role| %>
                <span class="role-config">
                  <%= role.name %>
                  <%= render_dropdown_menu do %>
                    <%= link_to(fa_icon('toggle-on', text: t('.select_group_role')), '#',
                          class: 'check-group-role', title: t('.select_group_role_hint'),
                          data: {role: role.id, group: controller, chkd: true}) %>
                    <%= link_to(fa_icon('toggle-off', text: t('.unselect_group_role')), '#',
                          class: 'check-group-role', title: t('.unselect_group_role_hint'),
                          data: {role: role.id, group: controller, chkd: false}) %>
                    <%= link_to(fa_icon('undo', text: t('.reset_group_role')), '#',
                        class: 'reset-group-role', title: t('.reset_group_role_hint'),
                        data: {role: role.id, group: controller}) %>
                  <% end %>
                </span>
              <% end %>
            </div>
            <ul class="order-list">
              <% permissions.each do |right, config| %>
                <li class="component right-row">
                  <span class="right-name">
                    <%= config["name"][locale.to_s] %>
                    <%= render_dropdown_menu do %>
                      <%= link_to(fa_icon('toggle-on', text: t('.select_right_roles')), '#',
                            class: 'check-right-roles', title: t('.select_right_roles_hint'),
                            data: {right: right, group: controller, chkd: true}) %>
                      <%= link_to(fa_icon('toggle-off', text: t('.unselect_right_roles')), '#',
                            class: 'check-right-roles', title: t('.unselect_right_roles_hint'),
                            data: {right: right, group: controller, chkd: false}) %>
                    <% end %>
                  </span>
                  <% @roles.each do |role| %>
                    <span class="role-config right-checkbox">
                      <%= render_toggle(
                            "role[#{role.id}][permissions][#{controller}][]",
                            right,
                            role.permissions_hash.fetch(controller,[]).include?(right),
                            id: "role_#{role.id}_permissions_#{controller}_#{right}",
                            data: {role: role.id, group: controller, right: right}
                          )
                      %>
                    </span>
                  <% end %>
                </li>
              <% end %>
            </ul>
          </div>
        </div>
      <% end %>
    </div>

    <div class="form-actions">
      <%= button_tag t("save"), class: 'btn btn-primary', disable_with: t("please_wait") %>
      <%= link_to t("back"), :back, class: "btn btn-default" %>
    </div>
  <% end %>

<% else %>
  <div class="alert alert-warning">
    <%= t(".none_role") %>
  </div>
<% end %>
<% content_for :stylesheets, stylesheet_link_tag("maxi_layout") %>
<% content_for :javascripts, javascript_include_tag("roles.index") %>

app/views/admin/roles/edit.html.erb
<%= render 'form' %>

app/views/admin/roles/index.html.erb
<% title ".roles" %>
<%= render 'roles_table' do %>
  <% if check_permission(Admin::RolesController, [:new]) %>
    <%= link_to t(".new_role"),
      new_admin_role_path,
      class: "btn btn-success" %>
  <% end %>
  <% if check_permission(Admin::UsersController, [:index]) %>
    <%= link_to t(".users"),
      main_app.admin_users_path,
      class: "btn btn-default" %>
  <% end %>
  <% if check_permission(Admin::UsersController, :manage_roles) %>
    <%= link_to t('.manage_roles'), manage_roles_admin_users_path, class: "btn btn-default" %>
  <% end %>
<% end %>

app/views/admin/roles/new.html.erb
<%= render 'form' %>