config/routes.rb
Rails.application.routes.draw do
  constraints(Weby::Subdomain) do

    get '/' => 'sites#show', as: :site
    get '/admin' => 'sites#admin', as: :site_admin
    get '/admin/edit' => 'sites#edit', as: :edit_site_admin
    get '/map' => 'sites/pages#sitemap', as: :sitemap_site_pages
    patch '/admin/edit' => 'sites#update', as: :update_site_admin
    delete '/admin/subsites/:id' => 'sites#destroy_subsite', as: :destroy_subsite_admin
    patch '/admin/subsites/:id' => 'sites#update_subsite', as: :update_subsite_admin

    resources :pages, as: :site_pages, controller: 'sites/pages', path: 'p', only: [:show]
    get '/fp', to: 'sites/pages#frame'
    get :pages, to: 'sites/pages#index', as: :site_pages
    get '/search', to: 'sites/searches#index', as: :searches
    #old routes
    get 'pages/:id(-:title)' => 'sites/pages#redirect', constraints: {id: /\d+/}

    resources :components,
              as: :site_components,
              controller: 'sites/components',
              only: [:show]

    post 'count/:model/:id' => 'application#count_click', as: :count_click

    namespace :admin, module: 'sites/admin', as: :site_admin do

      # route to paginate
      get 'repositories/page/:page' => 'repositories#index'
      get 'pages/page/:page' => 'pages#index'

      get 'stats' => 'statistics#index'
      get 'backups' => 'backups#index'
      get 'generate' => 'backups#generate'
      post 'import' => 'backups#import'

      resources :activity_records, only: [:index, :show]
      resources :extensions
      resources :menus do
        collection do
          post :change_order
        end
        resources :menu_items, controller: 'menus/menu_items' do
          member do
            put :toggle
          end
          collection do
            post :change_order, :change_menu
            delete :destroy_many
          end
        end
      end
      resources :pages do
        member do
          put :toggle, :recover
        end
        collection do
          get :recycle_bin
          delete :empty_bin, :destroy_many
        end
      end
      resources :repositories do
        member do
          get :crop
          put :recover
        end
        collection do
          get :recycle_bin
          delete :empty_bin, :destroy_many
        end
      end
      resources :roles, except: [:show] do
        collection do
          put :index
        end
      end
      resources :skins do
        member do
          post :apply
          get :preview
        end
        resources :components do
          member do
            put :toggle
            post :clone
          end
          collection do
            post :sort
            delete :destroy_many
          end
        end
        resources :styles do
          member do
            put :toggle, :copy, :follow, :unfollow
          end
          collection do
            post :sort
            delete :destroy_many
          end
        end
      end
      resources :users, only: [] do
        collection do
          get :manage_roles, :search
          post :change_roles, :create_local_admin_role, :set_preferences
          delete :destroy_local_admin_role
        end
      end
      resources :layouts, only: [] do
        collection do
          get :settings
          patch :settings, action: "update_settings"
        end
      end
    end

    Weby.extensions.each do |name, extension|
      constraints(extension) do
        require "#{name.to_s}/routes"
        instance_eval &("#{name.to_s.classify}::Routes".constantize.load)
      end
    end
  end

  root to: 'sites#index'

  constraints(Weby::GlobalDomain) do
    # route to paginate
    get 'sites/page/:page' => 'sites#index', as: :sites

    get '/admin' => 'application#admin'

    namespace :admin do
      match 'settings' => 'settings#index', via: [:get, :put]
      post 'settings/exec' => 'settings#exec', as: :exec
      resources :users do
        collection do
          get :manage_roles, :search
          post :change_roles
        end
        member do
          put :toggle
          put :set_admin
        end
      end
      resources :roles, except: :show do
        collection do
          put :index
          post :sort
        end
      end
      resources :sites, except: [:show] do
        member do
          put :toggle
          post :reindex
        end
      end
      resources :groupings, except: [:show]
      resources :notifications
      resources :activity_records, only: [:index, :show, :destroy]

      get 'stats' => 'statistics#index'

      # route to paginate
      get 'users/page/:page' => 'users#index'
      get 'sites/page/:page' => 'sites#index'
    end
  end

  # routes to profiles
  resources :profiles, only: [:show, :edit, :update], constraints: {id: /[^\/]+/} do
    member do
      get :history
    end
  end

  resources :notifications, only: [:index, :show] do
    collection do
      post :mark_as_read
    end
  end

  # defaults devise routes
  devise_for :users,
    path: '/',
    skip: [:sessions, :registrations, :passwords],
    controllers: { omniauth_callbacks: 'omniauth_callbacks' }

  # customize devise routes
  devise_scope :user do
    # routes to session
    delete 'logout'  => 'sessions#destroy'
    get 'login'   => 'sessions#new'
    post 'login'   => 'sessions#create'
    post 'link_user' => 'sessions#link_user'
    get 'new_user' => 'sessions#new_user'
    get 'shib_login/:hash' => 'sessions#shib_login', as: :shib_login

    # routes to register
    get 'signup'  => 'devise/registrations#new'
    post 'signup'  => 'registrations#create'

    # routes to password
    get 'forgot_password' => 'devise/passwords#new'
    post 'forgot_password' => 'passwords#create'
    get 'reset_password'  => 'devise/passwords#edit'
    put 'reset_password'  => 'devise/passwords#update'
  end

  get 'robots.txt' => 'sites#robots', format: 'txt'
  get '*not_found' => 'application#render_404'
end

app/models/skin.rb
class Skin < ApplicationRecord

  belongs_to :site

  has_many :components, dependent: :destroy
  has_many :root_components, -> { order(:position).where("place_holder !~ '^\\d*$'") }, class_name: 'Component'
  has_many :styles, -> { order('styles.position DESC') }, dependent: :destroy


  def base_theme
    Weby::Themes.theme(theme)
  end

  def layout
    base_theme.layout.merge(attributes[:layout].to_h)
  end

  #def components
  #  base_theme.components.merge(attributes[:components].to_h)
  #end

  def self.import(attrs, options = {})
    return attrs.each { |attr| import attr, options } if attrs.is_a? Array

    attrs = attrs.dup
    attrs = attrs['skin'] if attrs.key? 'skin'

    styles = attrs.delete('styles')
    components = attrs.delete('root_components')

    attrs.except!('id', 'created_at', 'updated_at', 'site_id', '@type', 'type')

    #search if this skin already exist
    skin = self.find_by theme: attrs['theme'], site_id: options[:site_id]
    if skin
      skin.update(attrs)
      #!!
      skin.components.destroy_all
      skin.styles.destroy_all

      newskin = skin
    else
      newskin = self.create!(attrs)
    end

    newskin.styles.import(styles)
    newskin.components.import(components, site_id: options[:site_id])
  end

  def components_yml
    list = root_components.group_by(&:place_holder)
    list = list.map do |place, comps|
      [
        place,
        comps.map.with_index do |comp, idx|
          json = comp.as_json(only: [:name, :alias, :position, :publish, :settings])
          json['position'] = idx+1
          parse_component_hash(json)
        end
      ]
    end.to_h.to_yaml
  end

  def get_variable name
    self.variables = '{}' if self.variables.blank?
    eval(variables)[name]
  end

  def get_variable_config name
    base_theme.variables[name].to_h.fetch('values', {})[get_variable(name)]
  end

  def set_variable name, value
    variables = '{}' if variables.blank?
    vars = eval(variables)
    vars[name] = value
    self.variables = vars.to_s
  end

  private

  def parse_component_hash json
    json.stringify_keys!
    json.delete('alias') if json['alias'].blank?
    case json['name']
    when 'menu'
      sett = eval(json['settings'])
      sett[:menu_id] = "%{menu_id}"
      json['settings'] = sett.to_s
      json['menu'] = {'name' => 'Principal'}
    when 'subsite_front_news'
      sett = eval(json['settings'])
      sett.delete(:sel_site)
      json['settings'] = sett.to_s
    when 'image'
      sett = eval(json['settings'])
      sett.delete(:repository_id)
      json['settings'] = sett.to_s
    when 'news_as_home'
      json['page'] = {'title' => 'Título', 'text' => 'Texto'}
    end
    if json['children'].blank?
      json.delete('children')
    else
      json['children'] = json['children'].map.with_index do |child, idx|
        parsed = parse_component_hash(child)
        parsed['position'] = idx+1
        parsed
      end
    end
    json
  end

end

app/controllers/sites/admin/skins_controller.rb
class Sites::Admin::SkinsController < ApplicationController
  before_action :require_user
  before_action :check_authorization, except: [:index, :show]
  before_action :load_skin, only: [:show, :destroy, :apply, :preview, :edit, :update]

  def index
    skins = current_site.skins.order(:name)
    if skins.empty?
      redirect_to new_site_admin_skin_path
    else
      active_skin = current_site.active_skin
      redirect_to site_admin_skin_path(active_skin.persisted? ? active_skin : skins.first)
    end
  end

  def show
    @active_skin = current_site.active_skin
    @skins = current_site.skins.order(:name).reject{|sk| sk.theme == @active_skin.theme }

    @components = @skin.components.includes(:skin).order(position: :asc)
    @placeholders = @skin.base_theme&.layout['placeholders']&.to_a

    @styles = {}
    @styles[:others] = Style.not_followed_by(@skin).search(params[:search])
                            .joins(:site).where(sites: {status: 'active'})
                            .order('sites.name, styles.name')
                            .page(params[:page]).per(params[:per_page])
    @styles[:styles] = @skin.styles.includes(:style, :followers, :site) if request.format.html? #.where(sites: {status: 'active'})
  end

  def new
    installed_themes = current_site.skins.pluck(:theme)
    @themes = Weby::Themes.all.reject{|th| installed_themes.include?(th.name) }.sort_by(&:name)
    if !current_user.is_admin
      @themes.reject!{|th| th.is_private }
    end
  end

  def create
    theme = ::Weby::Themes.theme(params[:theme])
    skin = current_site.skins.find_by(theme: theme.name)
    if theme.is_private && !current_user.is_admin
      flash[:error] = t('only_admin')
      redirect_to site_admin_skins_path
      return
    end
    if skin.blank?
      skin = current_site.skins.create(name: theme.name.titleize, theme: theme.name)
      record_activity('theme_installed', skin)
    else
      # should NOT call this action for themes already installed
      flash[:error] = t('theme_already_installed')
      redirect_to site_admin_skin_path(skin)
      return
    end

    alert = t('successfully_installed_theme')
    if params[:apply].to_s == 'true'
      current_site.skins.update_all active: false
      skin.update active: true
      record_activity('theme_applied', skin)
      alert = t('successfully_applied_theme')
    end

    theme.populate skin, user: current_user
    flash[:success] = alert
    redirect_to site_admin_skin_path(skin)
  end

  def edit
    @theme = @skin.base_theme
  end

  def update
    theme = @skin.base_theme
    theme.variables.each do |name, config|
      @skin.set_variable(name, params[name])
    end

    @skin.save!

    flash[:success] = t('.successfully_updated_theme')
    redirect_to site_admin_skin_path(@skin)
  end

  def apply
    current_site.skins.update_all active: false
    @skin.update active: true
    record_activity('theme_applied', @skin)
    flash[:success] = t('successfully_applied_theme')
    redirect_to site_admin_skin_path(@skin)
  end

  def preview
    redirect_to site_path(preview_skin: @skin.id)
  end

  def destroy
    @skin.components.destroy_all
    @skin.styles.destroy_all

    @skin.base_theme.populate @skin, user: current_user
    flash[:success] = t('.successfully_reseted_theme')
    record_activity('theme_reseted', @skin)
    redirect_to site_admin_skin_path(@skin)
  end

  private

  def load_skin
    @skin = current_site.skins.find(params[:id])
  end
end

app/views/sites/admin/skins/_list.html.erb
<% unless styles.empty? %>
  <div class="table-wrapper styles">
    <table class="table table-striped align-middle" id="style_list" data-url="<%= sort_site_admin_skin_styles_path(@skin) %>">
      <thead>
        <% with_permission(action: :sort, controller: Sites::Admin::StylesController) do %>
          <th class="grab-header"></th>
        <% end %>
        <th class="center sel-all"><%= check_box_tag :select_all, 1, false %></th>
        <th width="20%"> <%= t('.name') %> </th>
        <th width="30%"> <%= "#{t('.site')}/#{t('.followers')}" %> </th>
        <th width="15%"> <%= t('.updated_at') %> </th>
        <th width="5%" style="text-align: center;"> <%= t('.publish') %> </th>
        <th></th>
      </thead>
      <tbody>
        <% styles.each do |style| %>
          <% next if !style.owner.active? %>
          <tr id="sort_style_<%= style.id %>" class="<%= "deactivated" unless style.publish %>">
            <% with_permission(action: :sort, controller: Sites::Admin::StylesController) do %>
              <td class="grab-cell"><%= link_to image_tag('drag.png'), '#', class: 'handle', title: t('move') %></td>
            <% end %>
            <td class="center sel-item"><%= check_box_tag :select_item, style.id, false %></td>
            <td>
              <% if style.style_id %>
                <%= icon('retweet') %>
                <%= link_to(style.name, site_admin_skin_style_path(style.skin_id, style)) %>
              <% else %>
                <% if check_permission(Sites::Admin::StylesController, [:edit]) %>
                  <%= link_to "#{style.name} #{content_tag(:span, icon(:edit), class: 'oh-c-i')}".html_safe, edit_site_admin_skin_style_path(@skin, style) %>
                <% else %>
                  <%= link_to style.name, site_admin_skin_style_path(style.skin_id, style) %>
                <% end %>
              <% end %>
            </td>
            <td> <%= style.style ?
                      link_to( style.owner.name, site_url(subdomain: style.owner), target: :_blank, title: style.owner.title) :
                      style.followers.each.map{|site| link_to site.name, site_url(subdomain: site), title: site.title, target: :_blank }.join(', ').html_safe
                 %>
            </td>
            <td> <%= l(style.original.updated_at, format: :short) %></td>
            <td class="publish" style="text-align: center;"><%= raw toggle_field(style, 'publish', 'toggle', controller: :styles, skin_id: style.skin_id, remote: true) %></td>
            <td class="actions text-right">
              <%= render_dropdown_menu do %>
                <%= style_menu(style) %>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <%= render_bulk_actions do %>
      <% with_permission(action: :destroy_many, controller: Sites::Admin::StylesController) do %>
        <%= link_to icon('trash', text: t('destroy')), destroy_many_site_admin_skin_styles_path(@skin), class: 'btn btn-sm btn-default destroy-many', method: :delete, data: {confirm: t('are_you_sure_del_many')} %>
      <% end %>
    <% end %>
  </div>
<% else %>
  <div class="alert alert-warning">
    <%= t('.no_styles') %>
  </div>
<% end %>

app/views/sites/admin/skins/_others.html.erb
<div class="row">
  <div class="col-md-5">
    <%= form_tag site_admin_skins_path(anchor: 'tab-styles'), method: 'get', name: 'style_search', remote: true, class: 'search' do %>
      <%= search_input params[:search] %>
    <% end %>
  </div>
</div>

<% unless styles.blank? %>
 <div class="styles" id="other_styles">
  <table class="table table-striped align-middle">
    <thead>
      <th width="34%"> <%= t('.name') %> </th>
      <th width="25%"> <%= t('.site') %> </th>
      <th width="18%"> <%= t('.updated_at') %> </th>
      <th></th>
    </thead>
    <tbody>
      <% styles.group_by{ |style| style.skin.site }.each do |site, site_styles| %>
        <tr><td colspan="4" class="site-style-group">
          <%= content_tag :span, class: "toggle-styles", data: {site: site.id} do %>
            <%= icon('chevron-down') %> <b><%= site.title %> <span class="label label-info"><%= site.skins.find_by(theme: @skin.theme).styles.own.size %></span></b>
          <% end %>
        </td></tr>
        <% site_styles.each do |style| %>
          <tr class="style-site-<%= site.id %>">
            <td><%= link_to(style.name, site_admin_skin_style_path(style.skin_id, style)) %></td>
            <td><%= link_to style.site.name, site_url(subdomain: style.site), title: style.site.title, target: :_blank %></td>
            <td><%= l(style.updated_at, format: :short) %>
            <td class="actions text-right">
              <%= render_dropdown_menu do %>
                <%= style_menu(style) %>
              <% end %>
            </td>
          </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>
  <%= paginate styles, remote: true %>
 </div>
<% else %>
  <div class="alert alert-warning">
    <%= t(".no_other_styles") %>
  </div>
<% end %>

app/views/sites/admin/skins/edit.html.erb
<% title ".themes" %>
<% breadcrumb :skins_edit %>

<%= simple_form_for [:site_admin, @skin] do |f| %>

  <% if @theme.variables.blank? %>
    <div class="alert alert-warning">
      <%= t(".no_settings") %>
    </div>

    <div class="form-actions">
      <%= link_to t("back"), :back, class: "btn btn-default" %>
    </div>
  <% else %>

    <% @theme.variables.each do |name, config| %>
      <div class="form-group string optional">
        <label class="string optional" for="code"><%= t('themes.'+@skin.theme+'.variables.'+name) %></label>
        <% if config['type'] == 'color' %>
          <% grouped_options = config['values'].group_by{ |option_name, object| object['group'] } %>
          <% grouped_options.each do |group, option| %>
            <%= "<div class=\"group-title\">#{config['groups'][group][current_locale.to_s]}</div>".html_safe if group.present? %>
            <div class="color-pick-container">
              <% option.each do |option_name, object| %>
                <div class="color-pick-option">
                  <%= radio_button_tag name, option_name, @skin.get_variable(name) == option_name, id: "color-#{option_name}" %>
                  <label style="background-color: <%= object['main'] %>;" for="<%= "color-#{option_name}" %>"></label>
                  <div class="sub-color"></div>
                </div>
              <% end %>
            </div>
          <% end %>
        <% end %>
      </div>
    <% end %>

    <div class="form-actions">
      <%= f.submit class: 'btn btn-primary' %>
      <%= link_to t("back"), :back, class: "btn btn-default" %>
    </div>

  <% end %>
<% end %>

app/views/sites/admin/skins/new.html.erb
<% title ".themes" %>
<% breadcrumb :skins_new %>

<div class="row">
  <% if @themes.each do |theme| %>
    <div class="col-md-3">
      <div class="thumbnail">
        <h3 class="text-center"><%= theme.title %></h3>
        <div class="caption">
          <%= image_tag "#{theme.name}/thumb.png", style: 'width: 160px' %>
        </div>
        <div class="caption">
          <%= link_to(t('.install'), site_admin_skins_path(theme: theme.name), method: :post, class: 'btn btn-success btn-block') if check_permission(Sites::Admin::SkinsController, [:create]) %>
          <%= link_to(t('.install_apply'), site_admin_skins_path(theme: theme.name, apply: true), method: :post, class: 'btn btn-primary btn-block', data: {confirm: t('.confirm_apply')}) if check_permission(Sites::Admin::SkinsController, [:create]) %>
        </div>
      </div>
    </div>
  <% end.empty? %>
    <div class="col-md-12">
      <div class="alert alert-warning">
        <%= t(".no_themes") %>
      </div>
    </div>
  <% end %>
</div>
<div class="form-actions">
  <%= link_to t("back"), :back, class: "btn btn-default" %>
</div>

app/views/sites/admin/skins/show.html.erb
<% title ".themes" %>
<% breadcrumb :skins_show, @skin %>

<% content_for :javascripts, javascript_include_tag('repositories.index') %>

<div class="row">
  <div class="col-md-12">
    <% if !@active_skin.persisted? %>
      <div class="pull-left">
        <span class="label label-danger"><%= t('.no_theme') %></span>
      </div>
    <% end %>
    <div class="pull-right">
      <% with_permission(action: :create) do %>
        <%= link_to icon('plus-sign', text: t(".install_theme")),
            new_site_admin_skin_path,
            class: "btn btn-success" %>
      <% end %>
      <% if current_user.is_admin? || current_user.is_local_admin?(current_site) %>
          <%= link_to t('.head'), settings_site_admin_layouts_path, class: "btn btn-default" %>
        <% end %>
    </div>
  </div>
</div>
<ul class="nav nav-tabs" id="theme-tabs">
  <% if @active_skin.persisted? %>
    <li class="current <%= 'active' if @active_skin.theme == @skin.theme %>">
      <div class="skin-tooltip label label-success"><%= t('.active_theme') %></div>
      <%= link_to(@active_skin == @skin ? '#' : site_admin_skin_path(@active_skin)) do %>
        <div><%= @active_skin.base_theme.title %></div>
        <%= image_tag "#{@active_skin.theme}/thumb.png", style: 'width: 85px' %>
      <% end %>
    </li>
  <% end %>
  <% with_permission(action: :index) do %>
    <% @skins.each do |skin| %>
      <% next unless skin.base_theme %>
      <li class="<%= 'active' if skin.theme == @skin.theme %>">
        <%= link_to(skin == @skin ? '#' : site_admin_skin_path(skin)) do %>
          <div><%= skin.base_theme.title %></div>
          <%= image_tag "#{skin.theme}/thumb.png", style: 'width: 85px' %>
        <% end %>
      </li>
    <% end %>
  <% end %>
</ul>
<div class="row">
  <div class="col-md-12">
    <div class="pull-right">
      <% if @skin != @active_skin %>
        <% with_permission(action: :create) do %>
          <%#= simple_form_for current_site, url: apply_site_admin_skin_path(@skin), method: :post do |f| %>
            <!-- <button type="submit" class="btn btn-success"><%= t('.apply') %></button> -->
          <%# end %>
          <%= link_to t('.apply'), apply_site_admin_skin_path(@skin), method: :post, class: 'btn btn-primary', data: {confirm: t('.confirm_apply')} %>
        <% end %>
        <% with_permission(action: :preview) do %>
          <%= link_to t(".preview"),
              preview_site_admin_skin_path(@skin),
              class: "btn btn-default", target: :_blank %>
        <% end %>
      <% end %>
      <% with_permission(action: :create) do %>
        <%= link_to t('.settings'), edit_site_admin_skin_path(@skin), class: 'btn btn-default' %>
      <% end %>
      <% with_permission(action: :destroy) do %>
        <%= link_to t('.default'), site_admin_skin_path(@skin), method: :delete, class: 'btn btn-default', data: {confirm: t('.confirm_default')} %>
      <% end %>
    </div>
  </div>
</div>
<% @can_layout = check_permission(Sites::Admin::ComponentsController, [:index]) %>
<% @can_style = check_permission(Sites::Admin::StylesController, [:index]) %>
<ul class="nav nav-tabs" id="tabs">
  <% if @can_layout %>
    <li class="active"><%= link_to('Layout', '#tab-layout', data: {toggle: :tab}) %></li>
  <% end %>
  <% if @can_style %>
    <li class="<%= 'active' unless @can_layout || @can_theme %>"><%= link_to(t('.styles'), '#tab-styles', data: {toggle: :tab}) %></li>
  <% end %>
</ul>

<div class="tab-content">
  <% if @can_layout %>
    <div role="tabpanel" class="tab-pane active" id="tab-layout">
      <p class="pull-right">
        <% if check_permission(Sites::Admin::ComponentsController, [:new]) %>
          <%= link_to icon('plus-sign', text: t(".new_component")),
            new_site_admin_skin_component_path(@skin),
            class: "btn btn-success" %>
        <% end %>
        <% if current_user.is_admin? %>
          <%= link_to icon('download-alt'), site_admin_skin_components_path(@skin, format: :yaml), class: 'btn btn-default', title: 'Download YML' %>
        <% end %>
      </p>
      <div class="clearfix form-group"></div>

      <div class="maxi_layout" data-sorturl="<%= sort_site_admin_skin_components_path(@skin) %>">
      <% @placeholders.each do |row| %>
        <%= content_tag :div, class: "maxi_level #{row["names"].many? ? "multi" : "single"}" do %>
          <% row["names"].each_with_index do |name, idx| %>
            <%= content_tag :div, class: "placeholder", data: {place: name}, style: "width: #{row["widths"] ? row["widths"][idx] : 100/row["names"].size}%;" do %>
              <%= link_to image_tag('add-row-w.svg'), new_site_admin_skin_component_path(@skin, placeholder: name), class: "add-btn btn btn-success btn-sm add-subitem", title: t(".new_component") if check_permission(Sites::Admin::ComponentsController, 'new') %>
              <div class="placeholder-name"><%= t("themes.#{@skin.theme}.placeholders.#{name}") %></div>
                <ul class="order-list" data-place="<%= name %>">
                  <% components_per_holder = @components.select{|component| component.place_holder == name} %>
                  <% if components_per_holder.empty? %>
                    <!--<div><i><%#= t(".empty_placeholder") %></i></div>-->
                  <% end %>

                  <% components_per_holder.each do |comp| %>
                    <% component = Weby::Components.factory(comp) %>
                    <%= list_component(component) %>

                  <% end %>
                  <% @components = @components - components_per_holder %>
                </ul>
            <% end %>
          <% end %>
        <% end %>
      <% end %>
      </div>

      <% if @components.any? %>
        <div class="placeholder-name"><%= t(".leftout_components") %></div>
        <div id="leftout" class="placeholder">
          <ul>
          <%# Se sobrou algum component com placeholder que não está no layout atual %>
          <% @components.each do |comp| %>
              <% component = Weby::Components.factory(comp) %>
              <%= list_component(component, true) %>
          <% end %>
          </ul>
        </div>
      <% end %>
    </div>
  <% end %>
  <% if @can_style %>
    <div role="tabpanel" class="tab-pane <%= 'active' unless @can_layout || @can_theme %>" id="tab-styles">
      <% with_permission action: :new, controller: Sites::Admin::StylesController do %>
        <div class="pull-right">
          <%= link_to t(".new_style"),
            new_site_admin_skin_style_path(@skin),
            class: "btn btn-success" %>
        </div>
        <div class="clearfix form-group"></div>
      <% end %>

      <div class="tabbable">
        <ul class="nav nav-tabs" id="style-tab">
          <li class="<%= params["others"] ? "" : "active" %>" >
            <a href="#styles" data-toggle="tab"><%= t(".my_styles") %></a>
          </li>
          <li class="<%= params["others"] ? "active" : "" %>" >
            <a href="#others" data-toggle="tab"><%= t(".others") %></a>
          </li>
        </ul>
        <div class="tab-content">
          <div class="tab-pane <%= params["others"] ? "" : "active" %>" id="styles">
            <%= render partial: 'list', locals: { styles: @styles.delete(:styles) } %>
          </div>
          <div class="tab-pane <%= params["others"] ? "active" : "" %>" id="others">
            <%= render partial: 'others', locals: { styles: @styles.delete(:others) } %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>
<% content_for :stylesheets, stylesheet_link_tag("sortable") %>
<% content_for :stylesheets, stylesheet_link_tag("maxi_layout") %>

<% content_for :javascripts, javascript_include_tag("init/sortable") %>
<% content_for :javascripts, javascript_include_tag("skins") %>

app/views/sites/admin/skins/show.js.erb
$('#others').
  html("<%=escape_javascript render(partial: "others", locals: { styles: @styles.delete(:others) }) %>");

initStyleCollapse();