config/routes.rb
Rails.application.routes.draw do
  constraints(Weby::Subdomain) do

    get '/' => 'sites#show', as: :site
    get '/admin' => 'sites#admin', as: :site_admin
    get '/admin/edit' => 'sites#edit', as: :edit_site_admin
    get '/map' => 'sites/pages#sitemap', as: :sitemap_site_pages
    patch '/admin/edit' => 'sites#update', as: :update_site_admin
    delete '/admin/subsites/:id' => 'sites#destroy_subsite', as: :destroy_subsite_admin
    patch '/admin/subsites/:id' => 'sites#update_subsite', as: :update_subsite_admin

    resources :pages, as: :site_pages, controller: 'sites/pages', path: 'p', only: [:show]
    get '/fp', to: 'sites/pages#frame'
    get :pages, to: 'sites/pages#index', as: :site_pages
    get '/search', to: 'sites/searches#index', as: :searches
    #old routes
    get 'pages/:id(-:title)' => 'sites/pages#redirect', constraints: {id: /\d+/}

    resources :components,
              as: :site_components,
              controller: 'sites/components',
              only: [:show]

    post 'count/:model/:id' => 'application#count_click', as: :count_click

    namespace :admin, module: 'sites/admin', as: :site_admin do

      # route to paginate
      get 'repositories/page/:page' => 'repositories#index'
      get 'pages/page/:page' => 'pages#index'

      get 'stats' => 'statistics#index'
      get 'backups' => 'backups#index'
      get 'generate' => 'backups#generate'
      post 'import' => 'backups#import'

      resources :activity_records, only: [:index, :show]
      resources :extensions
      resources :menus do
        collection do
          post :change_order
        end
        resources :menu_items, controller: 'menus/menu_items' do
          member do
            put :toggle
          end
          collection do
            post :change_order, :change_menu
            delete :destroy_many
          end
        end
      end
      resources :pages do
        member do
          put :toggle, :recover
        end
        collection do
          get :recycle_bin
          delete :empty_bin, :destroy_many
        end
      end
      resources :repositories do
        member do
          get :crop
          put :recover
        end
        collection do
          get :recycle_bin
          delete :empty_bin, :destroy_many
        end
      end
      resources :roles, except: [:show] do
        collection do
          put :index
        end
      end
      resources :skins do
        member do
          post :apply
          get :preview
        end
        resources :components do
          member do
            put :toggle
            post :clone
          end
          collection do
            post :sort
            delete :destroy_many
          end
        end
        resources :styles do
          member do
            put :toggle, :copy, :follow, :unfollow
          end
          collection do
            post :sort
            delete :destroy_many
          end
        end
      end
      resources :users, only: [] do
        collection do
          get :manage_roles, :search
          post :change_roles, :create_local_admin_role, :set_preferences
          delete :destroy_local_admin_role
        end
      end
      resources :layouts, only: [] do
        collection do
          get :settings
          patch :settings, action: "update_settings"
        end
      end
    end

    Weby.extensions.each do |name, extension|
      constraints(extension) do
        require "#{name.to_s}/routes"
        instance_eval &("#{name.to_s.classify}::Routes".constantize.load)
      end
    end
  end

  root to: 'sites#index'

  constraints(Weby::GlobalDomain) do
    # route to paginate
    get 'sites/page/:page' => 'sites#index', as: :sites

    get '/admin' => 'application#admin'

    namespace :admin do
      match 'settings' => 'settings#index', via: [:get, :put]
      post 'settings/exec' => 'settings#exec', as: :exec
      resources :users do
        collection do
          get :manage_roles, :search
          post :change_roles
        end
        member do
          put :toggle
          put :set_admin
        end
      end
      resources :roles, except: :show do
        collection do
          put :index
          post :sort
        end
      end
      resources :sites, except: [:show] do
        member do
          put :toggle
          post :reindex
        end
      end
      resources :groupings, except: [:show]
      resources :notifications
      resources :activity_records, only: [:index, :show, :destroy]

      get 'stats' => 'statistics#index'

      # route to paginate
      get 'users/page/:page' => 'users#index'
      get 'sites/page/:page' => 'sites#index'
    end
  end

  # routes to profiles
  resources :profiles, only: [:show, :edit, :update], constraints: {id: /[^\/]+/} do
    member do
      get :history
    end
  end

  resources :notifications, only: [:index, :show] do
    collection do
      post :mark_as_read
    end
  end

  # defaults devise routes
  devise_for :users,
    path: '/',
    skip: [:sessions, :registrations, :passwords],
    controllers: { omniauth_callbacks: 'omniauth_callbacks' }

  # customize devise routes
  devise_scope :user do
    # routes to session
    delete 'logout'  => 'sessions#destroy'
    get 'login'   => 'sessions#new'
    post 'login'   => 'sessions#create'
    post 'link_user' => 'sessions#link_user'
    get 'new_user' => 'sessions#new_user'
    get 'shib_login/:hash' => 'sessions#shib_login', as: :shib_login

    # routes to register
    get 'signup'  => 'devise/registrations#new'
    post 'signup'  => 'registrations#create'

    # routes to password
    get 'forgot_password' => 'devise/passwords#new'
    post 'forgot_password' => 'passwords#create'
    get 'reset_password'  => 'devise/passwords#edit'
    put 'reset_password'  => 'devise/passwords#update'
  end

  get 'robots.txt' => 'sites#robots', format: 'txt'
  get '*not_found' => 'application#render_404'
end

app/views/sites/admin/pages/_form.html.erb
<%= simple_form_for [:site_admin, @page] do |f| %>
  <%= f.show_errors %>

  <%= render('translates_form', f: f) %>

  <%= f.input :publish, wrapper_html: { class: "side" }, 
    as: :boolean,
    input_html: { class: "check-button" },
    wrapper: :checkbox %>

  <%= repository_search t(".related_files"),
    "related_file_ids", "page[related_file_ids][]", @page.related_files,
    multiple: true, file_types: false %>
  
  <div class="form-actions">
    <%= f.button :submit, class: 'btn btn-primary', disable_with: t("please_wait") %>
    <%= link_to t("back"), :back, class: "btn btn-default" %>
  </div>
<% end %>

<% content_for :javascripts, javascript_include_tag("pages.form") %>
<% content_for :stylesheets, stylesheet_link_tag("datetime") %>

app/views/sites/admin/pages/_list.html.erb
<% if @pages.empty? %>
  <div class="alert alert-warning">
    <%= t(".none_page") %>
  </div>
<% else %>
  <div class="pull-left"> <%= info_page @pages %> </div>
  <div class="pull-right"> <%= paginate @pages, remote: true %> </div>
  <div class="clearfix"></div>
  <div class="table-wrapper">
    <table class="table table-striped nowrap align-middle">
      <thead>
        <tr>
          <th class="center sel-all"><%= check_box_tag :select_all, 1, false %></th>
          <th width="35%"><%= t(".title") %></th>
          <th width="12%"><%= sortable 'users.first_name', t(".author") %></th>
          <th width="25%"><%= sortable 'pages.created_at', t(".created_at") %></th>
          <% with_permission(action: :show) do %>
            <th width="5%"><%= sortable 'pages.publish', t(".publish") %></th>
          <% end %>
          <th width="5%" class="center"><%= sortable 'pages.view_count', t(".views") %></th>
          <th width="5%" class="center"><%#= t(".action")%></th>
        </tr>
      </thead>
      <tbody>
        <% @pages.each do |page| %>
        <tr id="<%= page.id %>"<%= ' class="deactivated"'.html_safe unless page.publish? %>>
          <td class="center sel-item"><%= check_box_tag :select_item, page.id, false %></td>
          <td>
            <%= title_with_flags(page) %>
          </td>
          <td><%= page.user.first_name %></td>
          <td><%= l(page.created_at, :format => :short) %></td>
          <% with_permission(action: :show) do %>
            <td class="publish">
              <%= publication_status_page(page, remote: true) %></td>
          <% end %>
          <td width="5%" style="text-align:center;"><%= page.view_count %></td>
          <td class="actions">
            <%= render_dropdown_menu do %>
              <%= link_to icon('eye-open', text: t('show')), site_page_path(page), target: :_blank %>
              <% with_permission(action: :new) do %>
                <%= link_to fa_icon('files-o', text: t('copy')), new_site_admin_page_path(copy_from: page.id) %>
              <% end %>
              <%= make_menu(page, :except => "show", :with_text => true) %>
            <% end %>
          </td>
        </tr>
      <% end %>
      </tbody>
    </table>
    <%= render_bulk_actions do %>
      <% with_permission(action: :destroy_many) do %>
        <%= link_to icon('trash', text: t('destroy')), destroy_many_site_admin_pages_path, class: 'btn btn-sm btn-default destroy-many', method: :delete, data: {confirm: t('are_you_sure_del_many')} %>
      <% end %>
    <% end %>
  </div>

  <div class="pull-left"> <%= per_page_links @pages, true, :sm %> </div>
  <div class="pull-right"> <%= paginate @pages, remote: true %> </div>
  <div class="clearfix"></div>
<% end %>

app/views/sites/admin/pages/_list_popup.html.erb
<div class="search_bar">
  <%= form_tag main_app.site_admin_pages_path(template: 'list_popup'), method: 'get', autocapitalize: "off", class: 'search', remote: true do %>
    <div class="row">
      <div class="col-md-7">
        <%= search_input params[:search], placeholder: t('.search_pages'), button_class: 'btn-search-page' %>
      </div>
    </div>
    <%= hidden_field_tag 'page', 1 %>
    <%= hidden_field_tag 'per_page', "#{params[:per_page]}" %>
  <% end %>
  <div class="clearfix"></div>
</div>
<% if @pages %>
  <% if @pages.empty? %>
    <div class="alert alert-warning">
      <%= t(".none_page") %>
    </div>
  <% else %>
    <div class="page-results">
      <table class="list table table-striped">
        <thead>
          <th><%= t(".title") %></th>
          <th><%= sortable 'date_begin_at', t(".register_date")%></th>
        </thead>
        <tbody>
          <% @pages.each do |page| %>
            <tr data-id="<%= page.id%>" data-url="<%= site_page_path(page) %>" data-title="<%= page.title %>" data-type="<%= "Page" %>" class="cursor highlight target-item">
              <td><%= page.title %></td>
              <td><%= page.created_at.strftime('%d/%m/%y') %></td>
            </tr>
          <% end %>
        </tbody>
      </table>

      <div class="pull-right"> <%= paginate @pages, remote: true, size: :sm %> </div>
      <div class="pull-left"> <%= per_page_links @pages, true, :sm %> </div>
      <div class="clearfix"></div>
    </div>
  <% end %>
<% end %>

app/views/sites/admin/pages/_target_dialog_input.html.erb
<%# Não inclua essa partial diretamente, utilize a função helper 'target_dialog_input' %>
<% field_name = editable_url ? :url : target_name %>

<div class="input target_select" id="inputs-for-<%= field_name.to_s %>">
   <%= f.input field_name, :wrapper => :append do %>
      <%= f.input_field field_name, as: :string,
        disabled: !editable_url,
        value: editable_url ? f.object.send(field_name) : f.object.send(field_name).try(:title),
        placeholder: editable_url ? "" : t("target_dialog.none_selected"),
        data: {target_content: true, prefix: "#{target_name}", editable: editable_url}, class: 'url-field' %>
      <span class="input-group-btn">
        <%=  link_to t("target_dialog.select_target"), '#', class: 'target-btn btn btn-info' %>
      </span>
   <% end %>

   <%= f.input "#{target_name}_id", as: :hidden, input_html: {data: {target_id: true, prefix: "#{target_name}"}} %>
   <%= f.input "#{target_name}_type", as: :hidden, input_html: {data: {target_type: true, prefix: "#{target_name}"}} if polymorphic %>
</div>

app/views/sites/admin/pages/_translates_form.html.erb
<%= each_i18n_tab available_locales(@page) do |locale| %>
  <%= f.i18ns_fields_for(locale) do |g| %>
    <%= g.input :_destroy, wrapper: :checkbox, as: :boolean if g.object.try(:id) %>
    <%= g.input :title %>
    <%= g.input :text,
      input_html: {class: "mceAdvance", style: " height: 320px;"},
      as: :text %>
  <% end %>
<% end %>
<%= target_dialog %>

app/views/sites/admin/pages/edit.html.erb
<% title ".pages" %>
<% breadcrumb :pages_edit, @page %>
<%= render 'form' %>

app/views/sites/admin/pages/index.html.erb
<% title ".pages" %>
<% breadcrumb params[:search].present? ? :pages_search : :pages, params[:search] %>
<div class="row">
  <div class="col-md-5">
    <%= form_tag site_admin_pages_path, method: 'get', autocapitalize: "off", class: 'search' do %>
      <%= search_input params[:search] %>
    <% end %>
  </div>
  <div class="col-md-7">
    <div class="pull-right">
      <% with_permission(action: :new) do %>
        <%= link_to t(".new_page"),
            new_site_admin_page_path,
            class: "btn btn-success" %>
      <% end %>
      <% with_permission(action: [:recover, :purge]) do %>
        <%= link_to t("recycle_bin"), recycle_bin_site_admin_pages_path, class: "btn btn-default" %>
      <% end %>
      <% with_permission(controller: SitesController, action: [:edit]) do %>
        <%= link_to icon('cog'), edit_site_admin_path(anchor: 'tab-pages'), class: "btn btn-default", title: t('.settings') %>
      <% end %>
    </div>
  </div>
</div>

<div id="pages">
  <%= render :partial => "list" %>
</div>

<% content_for :javascripts, javascript_include_tag("pages.admin.index") %>

app/views/sites/admin/pages/index.js.erb
$('#pages').html('<%= escape_javascript(render(:partial => 'list')) %>');

app/views/sites/admin/pages/list_popup.js.erb
$('#modal_target_list #tab-pages').html("<%= escape_javascript(render(:partial => 'list_popup')) %>");

app/views/sites/admin/pages/new.html.erb
<% title ".pages"%>
<% breadcrumb :pages_new %>
<%= render 'form' %>

app/views/sites/admin/pages/recycle_bin.html.erb
<% title "recycle_bin" %>
<% breadcrumb :pages_recycle_bin %>
<div class="pull-right">
  <% with_permission(action: :new) do %>
    <%= link_to t(".new_page"),
      new_site_admin_page_path,
      class: "btn btn-success" %>
  <% end %>
  <% with_permission(action: :index) do %>
    <%= link_to t(".list_pages"), site_admin_pages_path, class: "btn btn-default" %>
  <% end %>
  <% with_permission(action: :destroy) do %>
    <%= link_to t("empty_bin"), empty_bin_site_admin_pages_path, class: "btn btn-default btn-danger #{'disabled' if @pages.empty?}", method: :delete, disabled: @pages.empty?, data: {confirm: t('confirm_empty_bin')} %>
  <% end %>
</div>
<div class="clearfix"></div>

<div id="pages">
  <% if @pages.empty? %>
    <div style="margin-top: 10px;" class="alert alert-warning">
      <%= t("empty_recycle_bin") %>
    </div>
  <% else %>
    <div class="pull-left"> <%= info_page @pages %> </div>
    <div class="pull-right"> <%= paginate @pages, remote: true %> </div>
    <div class="clearfix"></div>

    <table class="table table-striped nowrap align-middle">
      <thead>
        <tr>
          <th width="270px"><%= t(".title") %></th>
          <th width="90px"><%= sortable 'users.first_name', t(".author") %></th>
          <th width="120px"><%= sortable 'pages.deleted_at', t(".deleted_at") %></th>
          <th width="50px"></th>
        </tr>
      </thead>
      <tbody>
        <% @pages.each do |page| %>
          <tr id="<%= page.id %>">
            <td>
              <%= page.title %>
            </td>
            <td><%= page.user.first_name %></td>
            <td><%= l(page.deleted_at, :format => :short) %></td>
            <td class="actions text-right">
              <%= render_dropdown_menu do %>
                <%= recycle_bin_actions page, with_text: true %>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>

    <div class="pull-left"> <%= per_page_links @pages, true, :i %> </div>
    <div class="pull-right"> <%= paginate @pages, remote: true %> </div>
    <div class="clearfix"></div>
  <% end %>
</div>

app/views/sites/admin/pages/recycle_bin.js.erb
var page = $('<div><%= escape_javascript(render(template: 'sites/admin/pages/recycle_bin.html')) %></div>');
$('#pages').html(page.find('#pages').html());

app/views/sites/admin/pages/show.html.erb
<% title ".pages" %>
<% breadcrumb :pages_show, @page %>
<article class="page-show">

  <header>
    <%= raw available_flags(@page) if @page.locales.many? %>
    <h1><%= @page.title %></h1>
  </header>

  <p class="page-details details">
    <div class="author"><%= t(".authored", author: @page.user, created_at: l(@page.created_at, format: :short)) %></div>
    <% if @page.updated_at != @page.created_at %>
      <div class="date"><%= t(".updated_at", updated_at: l(@page.real_updated_at, format: :short)) %></div>
    <% end %>
  </p>

  <%= render partial: 'sites/shared/pages_show_actions' %>

  <div class="form-actions">
    <%= link_to icon('eye-open', text: t('show')), site_page_path(@page) if @page.publish || @page.user_id == current_user.id %>
    <%= make_menu(@page, :except => "show") %>
    <%= link_to icon('list', text: t(".list_all")), site_admin_pages_path %>
    <%= link_to icon('chevron-left', text: t("back")), :back %>
  </div>
</article>

app/views/sites/admin/pages/tiny_mce.js.erb
$('#page_list').html("<%= escape_javascript(render(:partial => ('tiny_mce'))) %>");